version: '3'
services:
  backend:
    image: cert-backend:latest
    env_file:
      - backend.env
    volumes:
      - backend:/var/www/backend
      - ../../backend/public/:/var/www/backend/public/
    expose:
      - 9000
  nginx:
    image: cert-nginx:latest
    depends_on:
      - backend
    volumes:
      - backend:/var/www/backend
      - ../nginx/app.conf:/etc/nginx/sites-available/app.conf
    expose:
      - 80
    ports:
      - '80:80'
      - '443:443'
volumes:
  backend: