version: '3'
services:
  backend:
    image: cert-backend:latest
    env_file:
      - backend.env
    volumes:
      - ../../backend:/var/www/backend
    expose:
      - 9000
  nginx:
    image: cert-nginx:latest
    depends_on:
      - backend
    volumes:
      - ../../backend:/var/www/backend
      - ../nginx/app.conf:/etc/nginx/sites-available/app.conf
      - ../nginx/letsencrypt/:/var/www/letsencrypt
    expose:
      - 80
    ports:
      - '80:80'
      - '443:443'